version: '3.7'

services:
  microservice1:
    build:
      context: ./microservice1
      dockerfile: Dockerfile
    image: ms1:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - microservice2
    networks:
      - mynetwork
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

  microservice2:
    build:
      context: ./microservice2
      dockerfile: Dockerfile
    image: ms2:latest
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
    depends_on:
      - microservice3
    networks:
      - mynetwork
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

  microservice3:
    build:
      context: ./microservice3
      dockerfile: Dockerfile
    image: ms3:latest
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
    depends_on:
      - microservice4
    networks:
      - mynetwork
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

  microservice4:
    build:
      context: ./microservice4
      dockerfile: Dockerfile
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=production
    networks:
      - mynetwork
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    image: ms:latest

networks:
  mynetwork:
    driver: overlay